# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 01:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_rvus', models.FloatField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('code_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('code_name',),
            },
        ),
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(verbose_name='visit date')),
                ('code_billed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rvu.BillingCode')),
            ],
            options={
                'ordering': ('visit_date',),
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_rvu_goal', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rvu.Provider'),
        ),
    ]
