# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingcode',
            options={'ordering': ('ordering', 'code_name')},
        ),
        migrations.AddField(
            model_name='billingcode',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
